version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
